# -*- coding: utf-8 -*-
"""background_clear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W5zuXbqUaZbZMl7TPr0YL_Eb15jhCze8
"""

from google.colab import drive
drive.mount('/content/drive')

# onnxruntime modülünü yükleyelim
!pip install onnxruntime

# Gerekli kütüphaneler
from rembg import remove
from PIL import Image
import io

# Görselin yolu
input_path = '/content/drive/MyDrive/arkaplan/logolar.png'

# Görseli açalım
with open(input_path, "rb") as input_file:
    input_data = input_file.read()

# Arka planı kaldırma işlemi
output_data = remove(input_data)

# Çıkan sonucu kaydedelim
output_image = Image.open(io.BytesIO(output_data))

# Çıkan görseli belirtilen yola kaydedelim
output_path = '/content/drive/MyDrive/arkaplan/logolar_arkaplansız.png'
output_image.save(output_path)

# Sonuç dosyasını kaydettiğimiz yolu yazdıralım
print(f"Arka planı kaldırılmış görsel kaydedildi: {output_path}")